export const ROUTE_PATHS = {
  DEFAULT: "/",
  PROFILE: "/profile",
  ADMIN: "/admin",
  LOGIN: "/login",
  REGISTER: "/register",
  SEARCH: "/search",
  FAVOURITE: "/favorites",
  BOOK_DETAIL: "/book-detail",
  RANK: "/community-rank",
  BOOK_EXCHANGE: "/book-exchange",
  BOOK: "/books",
  MANAGE_BOOK: "/books/new",
  AFFILIATE: "/affiliate-links",
  MANAGE_AFFILIATE: "/affiliate-links/new",
};
