export const ROUTE_PATHS = {
  DEFAULT: "/",
  PROFILE: "/profile/:username",
  ADMIN: "/admin",
  LOGIN: "/login",
  REGISTER: "/register",
  SEARCH: "/search",
  FAVOURITE: "/favorites",
  BOOK_DETAIL: "/book-detail/:bookId",
  RANK: "/community-rank",
  BOOK_EXCHANGE: "/book-exchange",
  NOT_FOUND: "/*",
  BOOK: "/books",
  MANAGE_BOOK: "/books/new",
  AFFILIATE: "/affiliate-links",
  MANAGE_AFFILIATE: "/affiliate-links/new",
  CATEGORY: "/categories",
  CREATE_CATEGORY: "/categories/create",
  CREATE_POST: "/create-post",
  COMMENT_REPORT: "/comment-reports",
  DETAIL_POST: "/post",
  POSTS: "/posts",
  MY_POSTS: "my-posts",
};
