name: Docker Image CI

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN_FE }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set image tag with commit SHA
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_TAG }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image with tag
        run: docker build ./ReadNest -f ./ReadNest/Dockerfile -t $IMAGE_TAG

      - name: Push Docker image to registry
        run: docker push $IMAGE_TAG

      - name: SSH to Server and Run Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/readnest/readnest
            docker create --name tmp-frontend ${{ secrets.DOCKER_TAG }}:${{ github.sha }}
            rm -rf ./nginx/html
            docker cp tmp-frontend:/usr/share/nginx/html ./nginx/html
            docker rm tmp-frontend
            docker-compose restart nginx
